### ISSUE TITLE
Add `include-fsi` for F# Interactive output

### ISSUE THREAD

**Issue by DmitriyVlasov** [fsprojects/FSharp.Formatting#336]
Dear colleagues.

In preparing the presentation "Overview FSharp 4.0" using [FsReveal](http://fsprojects.github.io/FsReveal/) in part "Rational exponents in units of measure" used the structure:

``` fsharp
open FSharp.Data.UnitSystems.SI.UnitSymbols 

[<Measure>] type cm 

(*** define-output:show-simple-measure ***)
let threeCm = 3<cm>

(*** include-output:show-simple-measure ***)
```

 Expecting to receive the output:

```
val threeCm : int<cm> = 3
```

But a blank line:

```

```

**PS:** Of course, in this situation, I came out of the situation and put the output in the form of constants. But, in my opinion, the document with a rich use of the measures would not be convenient.

**Comment by tpetricek** [comment]
The `(*** include-output: ... ***)` command includes whatever the snippet _prints_, but this does not print the output of F# Interactive. See the examples in the documentation: http://tpetricek.github.io/FSharp.Formatting/evaluation.html

We don't really have an option for including F# Interactive output :( the best you can do is probably to use `(*** include-value:threeCm ***)`, but that will only show the value - `3`.

It would be nice to have `include-fsi` or something. A PR would be welcome!

**Comment by matthid** [comment]
Note that Yaaf.FSharp.Scripting already supports retrieving the fsi output: https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L391
(Even a "merged" output, which is the same as fsi would print, is supported; because you can't reliably merge the outputs afterwards)

We "throw away" the info here: https://github.com/tpetricek/FSharp.Formatting/blob/d7ad558917047083188d1094cc00651fc104724b/src/FSharp.Literate/Evaluator.fs#L168

So it should not be too hard to add this feature.

**Comment by dsyme** [comment]
This is done, see the docs
