### ISSUE TITLE
[question] []`1 doesn't have a qualified name

### ISSUE THREAD

**Issue by haf** [fsprojects/FSharp.Formatting#364]
```
FSharp.Formatting Error: 0 : Error while building member-name for Suave.Compression.transform because: the type '[]`1' does not have a qualified name
```

What does that mean?

**Comment by matthid** [comment]
This means that we accessed a property/method from FCS which has thrown an exception while trying to build the xml-sig name. The problem is that FCS doesn't always tell us the xmlsig name (the name used in the documentation xml file) especially on C# code. So every time we don't get a valid one we try to build it on our own.

There are however some members for which this is not possible as we cannot access some properties/methods (I guess because they are auto-generated by the compiler or something like that). However to notify the user that we may miss some documentation we trigger this error here: https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L792

In the log-file you can find the complete stack-trace...
So if you want to have further details you need to directly ask on the FSharp.Compiler.Service repository what this means in detail and if we can somehow detect this case without try-with.

**Comment by haf** [comment]
I get alot of these running the tool on Suave. Are we doing something special?

**Comment by matthid** [comment]
No, I get a lot of those as well, but I never had the motivation and time to find the root cause and fix it (ideally in FCS). However logging an error is correct as we might miss some members here...

**Comment by jackfoxy** [comment]
I get this error on some class type members. I can't see any obvious reason why it throws on some members, and not others. 

It appears from the FSharp.Formatting code the full errror can be, or is written to a log file. I haven't investigated further. The location of the log file was not immediately apparent to me, and I have not investigated further.

It looks like this has not been reported as an issue in FCS.

**Comment by jackfoxy** [comment]
The latest version I get of this is

````Error while building member-name for Jackfoxy.DomainLib.IntRange.NumRangeValidator because: not a named type````

@matthid  comment above from Dec 19, 2015 helpful in identifying where this error occurs.

### The bigger problem this causes

This causes FSharp.Formatting to fail on creating intellisense tool tips in the output. I have at least 2 github.io documentation projects where this is the case. And I'm sure others must experience it too.

### Possible solutions

1) This is only failing on individual members. Why doesn't FSharp.Formatting  successfully complete the tooltips? (Last I tried understanding the logic flows in this project was 3 years ago, without any success. Someone more familiar might know a way to fix this.)

2) Is there an issue to report to FCS?

**Comment by matthid** [comment]
1. like I said this is some implementation problem either on our or on fcs side (propably fcs but they might have some weird reason for it and we need to add a workaround)

2. yes the best way to get this fixed is to reproduce this without fsf and report to fcs... this is not overly complicated (just note in the debugger which fcs apis we call and repeat them), but a bit of work..
