### ISSUE TITLE
Suggestion: ApiDocs references in markdown

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#659]
The suggestion is that our markdown include an extension which uses the XML Doc name signature thing used by F# documentation references, e.g. 

    `cref:T:DiffSharp.UnaryOpElementwise`

In the DiffSharp documentation we're hitting many cases where markdown (whether in .fsx or .md source) needs to reference API docs.

At the moment you need to do something like this:

```
[`UnaryOpElementwise`](reference/diffsharp-unaryopelementwise.html)
```
 
This is error prone and involves knowing the details of the embedding and requires it to be stable.

**Comment by dsyme** [comment]
This is implemented in 10.0.3

**Comment by dsyme** [comment]
There are some examples of how to use this at https://fsprojects.github.io/FSharp.Formatting/content.html#Cross-References-to-API-Docs

**Comment by baronfel** [comment]
@dsyme On the published link the link for `cref:M:System.Console.WriteLine(System.String)` didn't resolve to the directly to the anchor for the specific overload, is that a problem? It resolved to `https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline` instead of the 'direct' link of `https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline?view=net-5.0#System_Console_WriteLine_System_String_`

**Comment by dsyme** [comment]
> @dsyme On the published link the link for cref:M:System.Console.WriteLine(System.String) didn't resolve to the directly to the anchor for the specific overload, is that a problem?

yes we're not doing that correctly as yet, we don't know how to generate the `#System_Console_WriteLine_System_String_` magix string.
