### ISSUE TITLE
Getting ReturnType from ApiDocMember without Html already embedded

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/FSharp.Formatting#708]
Is there a way to get the ReturnType name for a `ApiDocMember` signature without it already being wrapped in html?

# Actual

```fsharp
// Some library
let add a b = a + b

// do work to get ApiDocComment

let returnType = adm.ReturnInfo.ReturnType.Value  // <code>int</code>
```
## Desired

```fsharp
let returnType = adm.ReturnInfo.ReturnType.Value  // int
```

**Comment by MangelMaxime** [comment]
I was coming to ask the same question.

I tried to look at the information available via the debugger and I don't think there is one yet.

The HTML have some benefit of having the link generated to the referenced type:

```xml
<code><span><a href="/reference/nacara-core-types-pagecontext.html">PageContext</a>&#32;array</span></code>
```

However, in my case the generated HTML doesn't look like I want it to be. So I need to parse it to extract the information from it.

It would be nice to have the needed information to generate the HTML by ourself.

**Comment by dsyme** [comment]
@TheAngryByrd @MangelMaxime Are you after a textual representation of the type or the `FSharpType`?

On the whole the ApiDocsModel doesn't make `FSharpType` available except via the symbol but there's no real harm in doing it

**Comment by dsyme** [comment]
@MangelMaxime I added the FCS object for a bunch of the items here: https://github.com/fsprojects/FSharp.Formatting/pull/727

**Comment by MangelMaxime** [comment]
Hello @dsyme,

With the current situation of Nacara, I am after the instance of `FSharpType` or something equivalent which contains the type information resolved by FCS.

This is needed in order to:

1. Generates the textual representation in a way that allows customisation of the colors and styling.
2. Generates the links information only for the API that I know is documented. Avoid dead links or links that redirect to F# documentation when the types is not coming from FSharp.Core

Right now in Nacara, all the code shown at the top of the pages are generated from the FCS types like `FSharpType`, `FSharpGenericParameter`. 

The only exception is the `ReturnInfo` which use the HTML provided by F# formatting as at first I didn't find a way to access it. It seems like I found a workaround in the past according to my previous comments. But this is not as easy as doing `XXX.ReturnInfo.Type`

**Comment by dsyme** [comment]
Yup, this is done in #727, release should be coming through the pipe.
